PARAMETERS:
  NUM_INPUTS: 3
  NUM_OUTPUTS: 2
  TIME_STEP: 0.004 # Higher resolution needed

  g: 9.81
  m1: 2
  m2: 1
  l1: 2
  l2: 1

SETTINGS:
  save_collected: True

MODELS:
  PIDNN:
    model_name: pidnn
    num_layers: 8
    neurons_per_layer: 40
    training_is_border: False
    take_differential_points: True
    num_datadriven: -1 # To be filled by reader
    num_collocation: -1 # Filled as collocation_multiplier*num_datadriven
    collocation_multiplier: [2, 4, 6, 8, 10] # Hyperparameter for collocation points
    differential_order: 3

  FF:
    model_name: ff
    num_layers: 8
    neurons_per_layer: 40
    training_is_border: False
    take_differential_points: False
    num_datadriven: -1 # To be filled by reader
    num_collocation: 0
    collocation_multiplier: [0]

DATASETS:
  SIMULATION_30_40:
    NUM_SNAPSHOTS: 10000
    THETA_START: 30.0
    THETA_END: 40.0
    THETA_NUM: 6

    datadir: ./Data/simulation_00_03/
    testdirs: []
